//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("0.2.3")]
[assembly: AssemblyFileVersion("0.2.3.0")]
[assembly: AssemblyCopyright("Copyright (C) Southside Software, LLC 2013")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCompany("Southside Software, LLC")]
[assembly: AssemblyProduct("Support for driving some sort of external device off the status of one or more bu" +
    "ild configurations (Debug DB: 0)")]


